board/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BoardHome.as_view(), name='board_home'),
    url(r'^new/$', views.board_new, name='board_new'),
    url(r'^list/$', views.board_list, name='board_list'),
    url(r'^list/set$', views.board_set_list, name='board_set_list'),
    url(r'(?P<pk>\d+)/detail/', views.board_detail, name='board_detail'),
    url(r'(?P<pk>\d+)/edit/', views.board_edit, name='board_edit'),
    url(r'(?P<pk>\d+)/remove/', views.board_remove, name='board_remove'),
    url(r'^getboard', views.board_list_data, name='board_list_data')
]

custom/urls.py
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', custom_new, name='custom_new'),
    # url(r'^custom/$', CustomListView.as_view(), name='custom_list'),
    url(r'^custom/(?P<pk>\d+)/detail/$', custom_detail, name='custom_detail'),
    url(r'^custom/(?P<pk>\d+)/edit/$', custom_edit, name='custom_edit'),
    url(r'^custom/(?P<pk>\d+)/remove/$', CustomDeleteView.as_view(), name='custom_delete'),
    # url(r'^custom/(?P<pk>\d+)/comment/$', add_comment, name='add_comment'),
    url(r'^custom/(?P<pk>\d+)/comment/remove/$', comment_remove, name='comment_remove')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

urlpatterns = [
    url('^', include('custom.urls', namespace='custom')),
    url('^board/', include('board.urls', namespace='board')),
    url(r'^manager/$', ManagerHome.as_view(), name='manager_page'),
    # set, comment
    url(r'^manager/set/$', ManagerSetList.as_view(), name='manager_set_list'),
    url(r'^manager/comment/$',ManagerCommentList.as_view(), name='manager_comment_list'),
    # object compa
    url(r'^manager/compatible/$', ManagerCompaList.as_view(), name='manager_compa_list'),
    url(r'^manager/compatible/new$', ManagerCompaNew.as_view(), name='manager_compa_new'),
    url(r'^manager/compatible/(?P<pk>\d+)/edit$', ManagerCompaEdit.as_view(), name='manager_compa_edit'),
    url(r'^manager/compatible/(?P<pk>\d+)/remove$', manager_compa_remove, name='manager_compa_remove'),
    # object hardware
    url(r'^manager/hardware/$', ManagerHardwareList.as_view(), name='manager_hardware_list'),
    url(r'^manager/hardware/new$', ManagerHardwareNew.as_view(), name='manager_hardware_new'),
    url(r'^manager/hardware/(?P<pk>\d+)/edit$', ManagerHardwareUpdate.as_view(), name='manager_hardware_edit'),
    url(r'^manager/hardware/(?P<pk>\d+)/remove$', manager_hardware_remove, name='manager_hardware_remove'),
    #user
    url(r'^manager/user/$', ManagerUserList.as_view(), name='manager_user_list'),
    url(r'^manager/user/leave/$', leave, name='leave'),
    url(r'^manager/user/leave/done/$', leave_done, name='leave_done'),
    #stat
    url(r'^manager/stat$', ManagerStat.as_view(),name='manager_stat'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', RegisterView.as_view(), name='register'),
    url(r'^accounts/register/done$', RegisterDoneView.as_view(), name='register_done'),
    #user mypage
    url(r'^member/', MemberHome.as_view(), name='member_home'),
    url(r'^admin/', admin.site.urls),
    url(r'^no_authority', no_authority, name='no_authority'),
    # short
    url(r'^short/', portfolio_short, name='portfolio_short'),
    # AJAX
    url(r'^getcompa', get_compa, name='get_compa'),
    url(r'^getdata', get_data, name='get_data'),
    url(r'^gettext',get_text, name='get_text'),
    url(r'^getid',get_id, name='get_id'),
    url(r'^set', set, name='set'),
    url(r'^comment', comment, name='comment')
]

templates/member/leave_done.html
{% extends 'base.html' %}

{% block content %}
<div class="done_div">
    <h1>정상 처리 되었습니다.</h1>
</div>
<div class="button_area">
    <a href="/" class="button_st">메인화면</a>
</div>
{% endblock %}

templates/member/member_home.html
{% extends 'base.html' %}

{% block title %}My Page{% endblock %}

{% block content %}
{% load static %}
<div class="member_home">
    <div class="member_sect1 d_style">
        <h2>프로필</h2>
        <img src="{% static 'avatar/avatar-default.png' %}" alt="avatar"/>
        <p>{{ user.username }}</p>
        <p><a href="{% url 'password_change' %}" class="button_st">비밀번호 변경</a> <a href="#" class="button_st regist_out">회원탈퇴</a></p>
    </div>
    <div class="clearfix member_sect2">
        <div class="member_info1 d_style">
            <h2>내 견적</h2>
            <table>
                <tr>
                    <th>번호</th>
                    <th>견적</th>
                    <th>작성일</th>
                </tr>
                {% for set in sets %}
                <tr>
                    <td>{{ set.id }}</td>
                    <td><a href="{% url 'custom:custom_detail' pk=set.id %}">{{ set }}</a></td>
                    <td>{{ set.create_date|date:'Y.m.d h:i' }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">활동이 없습니다.</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="member_info2 d_style">
            <h2>내 댓글</h2>
            <table>
                <tr>
                    <th>번호</th>
                    <th>댓글</th>
                    <th>작성일</th>
                </tr>
                {% for ment in ments %}
                {% if ment.custom %}
                <tr>
                    <td>{{ ment.id }}</td>
                    <td><a href="{% url 'custom:custom_detail' pk=ment.custom.pk %}">{{ ment }}</a></td>
                    <td>{{ ment.create_date|date:'Y.m.d h:i' }}</td>
                </tr>
                {% elif ment.board %}
                <tr>
                    <td>{{ ment.id }}</td>
                    <td><a href="{% url 'board:board_detail' pk=ment.board.pk %}">{{ ment }}</a></td>
                    <td>{{ ment.create_date|date:'Y.m.d h:i' }}</td>
                </tr>
                {% endif %}
                {% empty %}
                <tr>
                    <td colspan="3">활동이 없습니다.</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<script>
    $('a.regist_out').click(function(){
        ans = confirm('정말 탈퇴 하시겠습니까?')
        if (ans === true) {
            location.href = '/manager/user/leave/'
        } else {
            alert('취소되었습니다.')
        }
    });
</script>
{% endblock %}