board/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BoardHome.as_view(), name='board_home'),
    url(r'^new/$', views.board_new, name='board_new'),
    url(r'^list/$', views.board_list, name='board_list'),
    url(r'^list/set$', views.board_set_list, name='board_set_list'),
    url(r'(?P<pk>\d+)/detail/', views.board_detail, name='board_detail'),
    url(r'(?P<pk>\d+)/edit/', views.board_edit, name='board_edit'),
    url(r'(?P<pk>\d+)/remove/', views.board_remove, name='board_remove'),
    url(r'^getboard', views.board_list_data, name='board_list_data')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

urlpatterns = [
    url('^', include('custom.urls', namespace='custom')),
    url('^board/', include('board.urls', namespace='board')),
    url(r'^manager/$', ManagerHome.as_view(), name='manager_page'),
    # set, comment
    url(r'^manager/set/$', ManagerSetList.as_view(), name='manager_set_list'),
    url(r'^manager/comment/$',ManagerCommentList.as_view(), name='manager_comment_list'),
    # object compa
    url(r'^manager/compatible/$', ManagerCompaList.as_view(), name='manager_compa_list'),
    url(r'^manager/compatible/new$', ManagerCompaNew.as_view(), name='manager_compa_new'),
    url(r'^manager/compatible/(?P<pk>\d+)/edit$', ManagerCompaEdit.as_view(), name='manager_compa_edit'),
    url(r'^manager/compatible/(?P<pk>\d+)/remove$', manager_compa_remove, name='manager_compa_remove'),
    # object hardware
    url(r'^manager/hardware/$', ManagerHardwareList.as_view(), name='manager_hardware_list'),
    url(r'^manager/hardware/new$', ManagerHardwareNew.as_view(), name='manager_hardware_new'),
    url(r'^manager/hardware/(?P<pk>\d+)/edit$', ManagerHardwareUpdate.as_view(), name='manager_hardware_edit'),
    url(r'^manager/hardware/(?P<pk>\d+)/remove$', manager_hardware_remove, name='manager_hardware_remove'),
    #user
    url(r'^manager/user/$', ManagerUserList.as_view(), name='manager_user_list'),
    url(r'^manager/user/leave/$', leave, name='leave'),
    url(r'^manager/user/leave/done/$', leave_done, name='leave_done'),
    #stat
    url(r'^manager/stat$', ManagerStat.as_view(),name='manager_stat'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', RegisterView.as_view(), name='register'),
    url(r'^accounts/register/done$', RegisterDoneView.as_view(), name='register_done'),
    #user mypage
    url(r'^member/', MemberHome.as_view(), name='member_home'),
    url(r'^admin/', admin.site.urls),
    url(r'^no_authority', no_authority, name='no_authority'),
    # short
    url(r'^short/', portfolio_short, name='portfolio_short'),
    # AJAX
    url(r'^getcompa', get_compa, name='get_compa'),
    url(r'^getdata', get_data, name='get_data'),
    url(r'^gettext',get_text, name='get_text'),
    url(r'^getid',get_id, name='get_id'),
    url(r'^set', set, name='set'),
    url(r'^comment', comment, name='comment')
]

board/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Board(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.ForeignKey('custom.User')
    created_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, null=True)

    def __str__(self):
        return self.title

board/forms.py
from django import forms
from .models import Board

class BoardForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ('title','category','text')

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core import serializers
from django.http import JsonResponse
from django.views.generic import TemplateView
from .models import Board,Category
from .forms import BoardForm
from custom.forms import CommentForm
from custom.models import Custom, User
from django.contrib.auth.decorators import login_required
# Create your views here.
class BoardHome(TemplateView):
    template_name = 'board/board_home.html'

    def get_context_data(self, **kwargs):
        context = super(BoardHome, self).get_context_data(**kwargs)
        context['custom'] = Custom.objects.all().order_by('-create_date')[:10]
        context['ctgrs'] = Category.objects.all()
        context['boards'] = Board.objects.all().order_by('-created_date')
        return context

def board_set_list(request):
    sets = Custom.objects.all()
    ctgrs = Category.objects.all()
    return render(request, 'board/board_set_list.html',{'sets':sets,'ctgrs':ctgrs})

def board_list(request):
    ctgr = request.GET.get('category')
    if ctgr != None:
        boards = Board.objects.filter(category__name = ctgr)
    else:
        boards = Board.objects.all()
    ctgrs = Category.objects.all()
    return render(request,'board/board_list.html',{'boards':boards,'ctgrs':ctgrs,'ctgr':ctgr})

def board_detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    cate = Category.objects.all()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('board:board_detail', pk=board.pk)
    else:
        form = CommentForm()

    return render(request, 'board/board_detail.html',{'board':board,'ctgrs':cate,'form':form})

@login_required
def board_new(request):
    cate = Category.objects.all()
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.save()
            return redirect('board:board_detail', pk=board.pk)
    else:
        form = BoardForm()
    return render(request, 'board/board_edit.html',{'form':form,'ctgrs':cate})

def board_edit(request, pk):
    board = get_object_or_404(Board, pk=pk)
    cate = Category.objects.all()
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.save()
            return redirect('board:board_detail', pk=board.pk)
    else:
        form = BoardForm(instance=board)
    return render(request, 'board/board_edit.html',{'form':form,'ctgrs':cate})

def board_remove(request, pk):
    board = get_object_or_404(Board, pk=pk)
    board.delete()
    return redirect('board:board_home')

def board_list_data(request):
    sets = serializers.serialize('json', Custom.objects.all())
    boards = serializers.serialize('json', Board.objects.all())
    ctgrname = serializers.serialize('json', Category.objects.all())
    id = serializers.serialize('json', User.objects.all())
    data = {
        'sets':sets,
        'boards':boards,
        'id':id,
        'ctgrname':ctgrname
    }
    return JsonResponse(data)

board/templates/board/add_board_comment.html
{% block board %}
<form action=""method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장</button>
</form>
{% endblock %}

board/templates/board/board_detail.html
{% extends 'board/board_home.html' %}

{% block board %}
<div class="board_detail">
    <h2>{{ board.title }}</h2>
    <p class="d_info">작성자 : {{ board.author }} 작성일 : {{ board.created_date|date:'Y년 m월 d일 h:i' }} {% if board.modified_date %}| 수정일 : {{ board.modified_date|date:'Y년 m월 d일 h:i' }}{% endif %}</p>
    <p class="d_text">{{ board.text }}</p>
    <p class="board_nav"><a href="{% url 'board:board_list' %}?category={{ board.category.id }}" class="button_st">목록</a><a href="{% url 'board:board_edit' pk=board.pk %}" class="button_st">수정</a><a class="button_st board_remove" id="{{ board.id }}">삭제</a></p>
</div>
    <div class="comment_area clearfix">
        {% if user.is_authenticated %}
        <h3>댓글</h3>
        {% include "custom/add_comment.html" %}
        {% endif %}
    </div>
    {% for comment in board.board_comments.all %}
    <div class="a_comment">
        <p class="comment_info">{{comment.author}} | {{comment.create_date|date:'Y년 m월 d일 h:i'}}</p>
        <p class="comment_text">{{comment.text}}</p>
        {% if user == set.user or user == comment.author or user.is_superuser %}
        <a href="#" class="ment_re button_st" id="{{ comment.id }}">댓글삭제</a>
        {% endif %}
    </div>
    {% empty %}
    <div class="a_comment">
        <p>등록된 댓글이 없습니다.</p>
    </div>
    {% endfor %}
<script>
    $('a.ment_re').click(function() {
        ment = confirm('정말 삭제하시겠습니까?')
        pk = $('a.ment_re').attr('id')
        if (ment === true) {
            location.href="/board/"+pk+"/comment/remove"
        } else {
            alert('취소되었습니다.')
        }
    })
    $('a.board_remove').click(function(){
        ment = confirm('정말 삭제하시겠습니까?')
        pk = $('a.board_remove').attr('id')
        if (ment === true) {
            location.href="/board/"+pk+"/remove"
        } else {
            alert('취소되었습니다.')
        }
    })
</script>
{% endblock %}

board/templates/board/board_edit.html
{% extends 'board/board_home.html' %}

{% block title %}새글쓰기{% endblock %}

{% block board %}
<h2>새글쓰기</h2>
<form action=""method="post" class="register uselabel">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="button_st form_button">저장</button>
</form>
{% endblock %}

board/templates/board/board_home.html
{% extends 'base.html' %}
{% block content %}
<div>
  <p>
    <h3>저장한 견적과 유저들이 작성한 글을 열람할 수 있는데 게시판입니다.</h3>
    *각 게시판마다 AngularJS 를 이용하였습니다.<br>
    <b>언어: Java Script 라이브러리: AngularJS</b>
  </p>
</div>
<div class="board_list_nav clearfix">
    <h3><a href="{% url 'board:board_home' %}">전체보기</a> | <a href="{% url 'board:board_set_list' %}">견적게시판</a> |{% for ctgr in ctgrs %} <a href="{% url 'board:board_list' %}?category={{ ctgr.id }}">{{ ctgr.name }} </a> |{% endfor %}</h3>
</div>
    {% block board %}
    <div class="board_list clearfix">
        {% verbatim %}
        <div class="board_list_ctgr d_style" ng-app="homeApp" ng-controller="homeCtrl">
            <h1>게시판</h1>
            <table>
                <tr>
                    <th>번호</th>
                    <th>견적</th>
                    <th>글쓴이</th>
                    <th>카테고리</th>
                    <th>작성일</th>
                </tr>
                <tr ng-repeat="board in boards|startFrom:currentPage*pageSize|limitTo:pageSize|orderBy:'-fields.created_date'">
                    <td>{{ board.pk }}</td>
                    <td><a href="{{ board.pk }}/detail">{{ board.fields.title }}</a></td>
                    <td>{{ board.username }}</td>
                    <td>{{ board.ctgr }}</td>
                    <td>{{ board.fields.created_date|date:'y.M.d h:m' }}</td>
                </tr>
            </table>
            <div class="button_area">
                <button ng-disabled="currentPage == 0" ng-click="currentPage=currentPage-1" class="button_st">이전</button>
                {{currentPage+1}}/{{numberOfPage()}}
                <button ng-disabled="currentPage >= boards.length/pageSize - 1" ng-click="currentPage=currentPage+1" class="button_st">다음</button>
            </div>
        {% endverbatim %}
            {% if user.is_authenticated %}
            <div class="board_home_new">
                <a href="/board/new/" class="board_new button_st">새글쓰기</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endblock %}
<script>
    var app = angular.module('homeApp', []);

    app.controller('homeCtrl', function($scope, $http) {
        $scope.currentPage = 0;
        $scope.pageSize = 10;
        $scope.boards = []
        $scope.numberOfPage = function() {
            return Math.ceil($scope.boards.length/$scope.pageSize);
        };
        $http.get('{% url "board:board_list_data" %}').then(function (response){
            $scope.data = JSON.parse(response.data.boards);
            $scope.id = JSON.parse(response.data.id);
            $scope.ctgr = JSON.parse(response.data.ctgrname);
            $scope.boards = $scope.data
            for (var i=0;i<$scope.boards.length;i++) {
                for (var k=0;k<$scope.id.length;k++) {
                    if ( $scope.boards[i]['fields']['author'] === $scope.id[k]['pk']) {
                        $scope.boards[i]['username'] = $scope.id[k]['fields']['username']
                    }
                    if ( $scope.boards[i]['fields']['category'] === $scope.ctgr[k]['pk'] ){
                        $scope.boards[i]['ctgr'] = $scope.ctgr[k]['fields']['name']
                    }
                }
            } 
        });
    });
    app.filter('startFrom', function() {
        return function(input, start) {
            start = +start;
            return input.slice(start);
        };
    });
</script>
{% endblock %}

board/templates/board/board_list.html
{% extends 'board/board_home.html' %}

{% block board %}
<h1 class="board_title">{% for cate in ctgrs %}{% if ctgr == cate.id|stringformat:"i" %}{{ cate }}{% endif %}{% endfor %}</h1>
{% verbatim %}
<div class="board_cate_list" ng-app="boardApp" ng-controller="boardCtrl">
    <table>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>글쓴이</th>
            <th>등록일</th>
        </tr>
        <tr ng-repeat="board in boards|startFrom:currentPage*pageSize|limitTo:pageSize|orderBy:'-fields.created_date'">
            <td>{{ board.pk }}</td>
            <td><a href="{{ board.pk }}/detail">{{ board.fields.title }}</a></td>
            <td>{{ board.username }}</td>
            <td>{{ board.fields.created_date|date:'y.M.d h:m' }}</td>
        </tr>
    </table>
    <div class="button_area">
        <button ng-disabled="currentPage == 0" ng-click="currentPage=currentPage-1" class="button_st">이전</button>
        {{currentPage+1}}/{{numberOfPage()}}
        <button ng-disabled="currentPage >= boards.length/pageSize - 1" ng-click="currentPage=currentPage+1" class="button_st">다음</button>
    </div>
</div>
{% endverbatim %}
{% if user.is_authenticated %}
<div class="board_home_new">
    <a href="{% url 'board:board_new' %}" class="board_new button_st">새글쓰기</a>
</div>
{% endif %}
<script>
    var app = angular.module('boardApp', []);

    app.controller('boardCtrl', function($scope, $http) {
        $scope.currentPage = 0;
        $scope.pageSize = 10;
        $scope.boards = []
        $scope.numberOfPage = function() {
            return Math.ceil($scope.boards.length/$scope.pageSize);
        };
        $http.get('{% url "board:board_list_data" %}').then(function (response){
            $scope.data = JSON.parse(response.data.boards);
            $scope.id = JSON.parse(response.data.id);
            for (var i=0;i<$scope.data.length;i++) {
                if ($scope.data[i]["fields"]["category"] == {{ ctgr }} ) {
                    $scope.boards.push($scope.data[i])
                }
            }
            for (var i=0;i<$scope.boards.length;i++) {
                for (var k=0;k<$scope.id.length;k++) {
                    if ( $scope.boards[i]['fields']['author'] === $scope.id[k]['pk']) {
                        $scope.boards[i]['username'] = $scope.id[k]['fields']['username']
                    }
                }
            } 
        });
    });
    app.filter('startFrom', function() {
        return function(input, start) {
            start = +start;
            return input.slice(start);
        };
    });
</script>
{% endblock %}

board/templates/board/board_set_list.html
{% extends 'board/board_home.html' %}

{% block board %}
<h1>견적게시판</h1>
{% verbatim %}
<div class="board_set_list" ng-app="setApp" ng-controller="setCtrl">
    <table>
        <tr>
            <th>번호</th>
            <th>견적</th>
            <th>글쓴이</th>
            <th>등록일</th>
        </tr>
        <tr ng-repeat="set in sets|startFrom:currentPage*pageSize|limitTo:pageSize">
            <td>{{ set.pk }}</td>
            <td><a href="/custom/{{ set.pk }}/detail">{{ set.title }}</a></td>
            <td>{{ set.username }}</td>
            <td>{{ set.fields.create_date|date:'y.M.d h:m' }}</td>
        </tr>
    </table>
    <div class="button_area">
    <button ng-disabled="currentPage == 0" ng-click="currentPage=currentPage-1" class="button_st">이전</button>
    {{currentPage+1}}/{{numberOfPage()}}
    <button ng-disabled="currentPage >= sets.length/pageSize - 1" ng-click="currentPage=currentPage+1" class="button_st">다음</button>
    </div>
    <a href="/" class="button_st">견적작성하기</a>
    <p>*견적게시판은 회원님들의 견적만 게시합니다.</p>
</div>
{% endverbatim %}
<script>
    var app = angular.module('setApp', []);

    app.controller('setCtrl', function($scope, $http) {
        $scope.currentPage = 0;
        $scope.pageSize = 10;
        $scope.sets = []
        $scope.numberOfPage = function() {
            return Math.ceil($scope.sets.length/$scope.pageSize);
        };
        $http.get('{% url "board:board_list_data" %}').then(function (response){
            $scope.data = JSON.parse(response.data.sets);
            $scope.id = JSON.parse(response.data.id);
            for (var i=0;i<$scope.data.length;i++) {
                if ($scope.data[i]['fields']['text'] != '') {
                    $scope.sets.push($scope.data[i])
                    $scope.sets[i]['title'] = $scope.data[i]['fields']['text'].slice(0,10)
                } else if ($scope.data[i]['fields']['text'] === '') {
                    $scope.sets.push($scope.data[i])
                    for (var k=0;k<$scope.id.length;k++) {
                        if ($scope.data[i]['fields']['user'] === $scope.id[k]['pk']) {
                            $scope.sets[i]['title'] = $scope.id[k]['fields']['username']
                        }
                    }
                }
                for (var k=0;k<$scope.id.length;k++) {
                    if ( $scope.sets[i]['fields']['user'] === $scope.id[k]['pk']) {
                        $scope.sets[i]['username'] = $scope.id[k]['fields']['username']
                    }
                }
            }
        });
    });

    app.filter('startFrom', function() {
        return function(input, start) {
            start = +start;
            return input.slice(start);
        };
    });
</script>
{% endblock %}