board/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BoardHome.as_view(), name='board_home'),
    url(r'^new/$', views.board_new, name='board_new'),
    url(r'^list/$', views.board_list, name='board_list'),
    url(r'^list/set$', views.board_set_list, name='board_set_list'),
    url(r'(?P<pk>\d+)/detail/', views.board_detail, name='board_detail'),
    url(r'(?P<pk>\d+)/edit/', views.board_edit, name='board_edit'),
    url(r'(?P<pk>\d+)/remove/', views.board_remove, name='board_remove'),
    url(r'^getboard', views.board_list_data, name='board_list_data')
]

custom/urls.py
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', custom_new, name='custom_new'),
    # url(r'^custom/$', CustomListView.as_view(), name='custom_list'),
    url(r'^custom/(?P<pk>\d+)/detail/$', custom_detail, name='custom_detail'),
    url(r'^custom/(?P<pk>\d+)/edit/$', custom_edit, name='custom_edit'),
    url(r'^custom/(?P<pk>\d+)/remove/$', CustomDeleteView.as_view(), name='custom_delete'),
    # url(r'^custom/(?P<pk>\d+)/comment/$', add_comment, name='add_comment'),
    url(r'^custom/(?P<pk>\d+)/comment/remove/$', comment_remove, name='comment_remove')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

urlpatterns = [
    url('^', include('custom.urls', namespace='custom')),
    url('^board/', include('board.urls', namespace='board')),
    url(r'^manager/$', ManagerHome.as_view(), name='manager_page'),
    # set, comment
    url(r'^manager/set/$', ManagerSetList.as_view(), name='manager_set_list'),
    url(r'^manager/comment/$',ManagerCommentList.as_view(), name='manager_comment_list'),
    # object compa
    url(r'^manager/compatible/$', ManagerCompaList.as_view(), name='manager_compa_list'),
    url(r'^manager/compatible/new$', ManagerCompaNew.as_view(), name='manager_compa_new'),
    url(r'^manager/compatible/(?P<pk>\d+)/edit$', ManagerCompaEdit.as_view(), name='manager_compa_edit'),
    url(r'^manager/compatible/(?P<pk>\d+)/remove$', manager_compa_remove, name='manager_compa_remove'),
    # object hardware
    url(r'^manager/hardware/$', ManagerHardwareList.as_view(), name='manager_hardware_list'),
    url(r'^manager/hardware/new$', ManagerHardwareNew.as_view(), name='manager_hardware_new'),
    url(r'^manager/hardware/(?P<pk>\d+)/edit$', ManagerHardwareUpdate.as_view(), name='manager_hardware_edit'),
    url(r'^manager/hardware/(?P<pk>\d+)/remove$', manager_hardware_remove, name='manager_hardware_remove'),
    #user
    url(r'^manager/user/$', ManagerUserList.as_view(), name='manager_user_list'),
    url(r'^manager/user/leave/$', leave, name='leave'),
    url(r'^manager/user/leave/done/$', leave_done, name='leave_done'),
    #stat
    url(r'^manager/stat$', ManagerStat.as_view(),name='manager_stat'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', RegisterView.as_view(), name='register'),
    url(r'^accounts/register/done$', RegisterDoneView.as_view(), name='register_done'),
    #user mypage
    url(r'^member/', MemberHome.as_view(), name='member_home'),
    url(r'^admin/', admin.site.urls),
    url(r'^no_authority', no_authority, name='no_authority'),
    # short
    url(r'^short/', portfolio_short, name='portfolio_short'),
    # AJAX
    url(r'^getcompa', get_compa, name='get_compa'),
    url(r'^getdata', get_data, name='get_data'),
    url(r'^gettext',get_text, name='get_text'),
    url(r'^getid',get_id, name='get_id'),
    url(r'^set', set, name='set'),
    url(r'^comment', comment, name='comment')
]

custom/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

class User(AbstractUser):
    is_manager = models.BooleanField(default=False)
    is_member = models.BooleanField(default=True)

class Hardware(models.Model):
    HARDWARE_KIND_CHOICE =(
        ('CPU','CPU'),
        ('BRD','Board'),
        ('RAM','RAM'),
        ('VGA','VGA'),
        ('POW','Power'),
        ('HDD','HDD'),
        ('SSD','SSD'),
        ('ODD','ODD'),
    )
    hardware_kind = models.CharField(
        max_length=3,
        choices=HARDWARE_KIND_CHOICE
    )
    name = models.CharField(max_length=100)
    option = models.TextField()
    hard_thumbnail = ProcessedImageField(
        upload_to='hardware',
        processors=[Thumbnail(55,55)],
        format='JPEG',
        options={'quality':60},
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    def hit(self):
        hard_count = 0;
        if self.hardware_kind == "CPU":
            req = Custom.objects.filter(cpu=self).count();
        elif self.hardware_kind == "BRD":
            req = Custom.objects.filter(board=self).count();
        elif self.hardware_kind == "RAM":
            req = Custom.objects.filter(ram=self).count();
        elif self.hardware_kind == "VGA":
            req = Custom.objects.filter(vga=self).count();
        elif self.hardware_kind == "POW":
            req = Custom.objects.filter(power=self).count();
        elif self.hardware_kind == "HDD":
            req = Custom.objects.filter(hdd=self).count();
        elif self.hardware_kind == "SSD":
            req = Custom.objects.filter(ssd=self).count();
        elif self.hardware_kind == "ODD":
            req = Custom.objects.filter(odd=self).count();
        some_hard = Hardware.objects.filter(hardware_kind=self.hardware_kind)
        for i in some_hard:
            if self.hardware_kind == "CPU":
                hard_count = hard_count + Custom.objects.filter(cpu=i.id).count();
            elif self.hardware_kind == "BRD":
                hard_count = hard_count + Custom.objects.filter(board=i.id).count();
            elif self.hardware_kind == "RAM":
                hard_count = hard_count + Custom.objects.filter(ram=i.id).count();
            elif self.hardware_kind == "VGA":
                hard_count = hard_count + Custom.objects.filter(vga=i.id).count();
            elif self.hardware_kind == "POW":
                hard_count = hard_count + Custom.objects.filter(power=i.id).count();
            elif self.hardware_kind == "HDD":
                hard_count = hard_count + Custom.objects.filter(hdd=i.id).count();
            elif self.hardware_kind == "SSD":
                hard_count = hard_count + Custom.objects.filter(ssd=i.id).count();
            elif self.hardware_kind == "ODD":
                hard_count = hard_count + Custom.objects.filter(odd=i.id).count();
        top = hard_count/100*85
        if req == 0:
            return ''
        elif req >= top:
            return 'HIT'

class Compa(models.Model):
    comp_mode = models.CharField(max_length=100)
    hardware = models.ManyToManyField(Hardware)

    def __str__(self):
        return self.comp_mode

    def cleaner(self):
        if self.hardware == None:
            self.delete()

class Custom(models.Model):
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)
    cpu = models.ForeignKey(Hardware,null=True,blank=True,related_name='cpu')
    board = models.ForeignKey(Hardware, null=True, blank=True,related_name='board')
    ram = models.ForeignKey(Hardware, null=True, blank=True,related_name='ram')
    vga = models.ForeignKey(Hardware, null=True, blank=True,related_name='vga')
    power = models.ForeignKey(Hardware, null=True, blank=True,related_name='power')
    hdd = models.ForeignKey(Hardware, null=True, blank=True,related_name='hdd')
    ssd = models.ForeignKey(Hardware, null=True, blank=True,related_name='ssd')
    odd = models.ForeignKey(Hardware, null=True, blank=True, related_name='odd')
    text = models.TextField(blank=True,null=True)

    def __str__(self):
        if self.text:
            return self.text[:10]
        else:
            return self.user.username

    class Meta:
        ordering = ['-create_date']

class Comment(models.Model):
    custom = models.ForeignKey('custom.Custom', related_name='custom_comments', null=True)
    board = models.ForeignKey('board.Board', related_name='board_comments', null=True)
    author = models.ForeignKey(User)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:10]

custom/forms.py
from django import forms
from .models import *

class CustomForm(forms.ModelForm):
    class Meta:
        model = Custom
        fields = ('cpu','board','ram','vga','power','hdd','ssd','odd','text',)
        widgets = {
            'cpu': forms.HiddenInput(),
            'board': forms.HiddenInput(),
            'ram': forms.HiddenInput(),
            'vga': forms.HiddenInput(),
            'power': forms.HiddenInput(),
            'hdd': forms.HiddenInput(),
            'ssd': forms.HiddenInput(),
            'odd': forms.HiddenInput(),
            'text': forms.HiddenInput(),
        }

class CustomUpdateForm(forms.Form,forms.ModelForm):
    class Meta:
        model = Custom
        fields = ('cpu','board','ram','vga','power','hdd','ssd','odd','text')
        widgets = {
            'cpu':forms.HiddenInput(),
            'board':forms.HiddenInput(),
            'ram':forms.HiddenInput(),
            'vga':forms.HiddenInput(),
            'power':forms.HiddenInput(),
            'hdd':forms.HiddenInput(),
            'ssd':forms.HiddenInput(),
            'odd':forms.HiddenInput(),
            'text':forms.HiddenInput(),
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

custom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import DeleteView, CreateView
from .models import *
from .forms import *
# 함수형 view

def custom_detail(request, pk):
    set = get_object_or_404(Custom, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.custom = set
            comment.author = request.user
            comment.save()
    else:
        form = CommentForm()

    return render(request, 'custom/custom_detail.html',{'set':set,'form':form})

def custom_new(request):
    cpu = Hardware.objects.filter(hardware_kind="CPU")[:10]
    board = Hardware.objects.filter(hardware_kind="BRD")[:10]
    ram = Hardware.objects.filter(hardware_kind="RAM")[:10]
    vga = Hardware.objects.filter(hardware_kind="VGA")[:10]
    power = Hardware.objects.filter(hardware_kind="POW")[:10]
    hdd = Hardware.objects.filter(hardware_kind="HDD")[:10]
    ssd = Hardware.objects.filter(hardware_kind="SSD")[:10]
    odd = Hardware.objects.filter(hardware_kind="ODD")[:10]
    if request.method == 'POST':
        form = CustomForm(request.POST)
        if form.is_valid():
            hard = form.save(commit=False)
            hard.user = request.user
            hard.save()
            return redirect('custom:custom_detail', pk=hard.pk)
    else:
        form = CustomForm()

    return render(request, 'custom/custom_new.html',{'form':form,'cpu':cpu,'board':board,'ram':ram,'vga':vga,'power':power,'hdd':hdd,'ssd':ssd,'odd':odd})

def custom_edit(request, pk):
    cpu = Hardware.objects.filter(hardware_kind="CPU")[:10]
    board = Hardware.objects.filter(hardware_kind="BRD")[:10]
    ram = Hardware.objects.filter(hardware_kind="RAM")[:10]
    vga = Hardware.objects.filter(hardware_kind="VGA")[:10]
    power = Hardware.objects.filter(hardware_kind="POW")[:10]
    hdd = Hardware.objects.filter(hardware_kind="HDD")[:10]
    ssd = Hardware.objects.filter(hardware_kind="SSD")[:10]
    odd = Hardware.objects.filter(hardware_kind="ODD")[:10]
    hard = get_object_or_404(Custom, pk=pk)
    if request.method == 'POST':
        form = CustomForm(request.POST, instance=hard)
        if form.is_valid():
            hard = form.save(commit=False)
            hard.user = request.user
            hard.save()
            return redirect('custom:custom_detail', pk=hard.pk)
    else:
        form = CustomUpdateForm(instance=hard)

    return render(request, 'custom/custom_new.html', {'form': form, 'hard': hard,'cpu':cpu,'board':board,'ram':ram,'vga':vga,'power':power,'hdd':hdd,'ssd':ssd,'odd':odd})

def custom_detail(request, pk):
    set = get_object_or_404(Custom, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.custom = set
            comment.author = request.user
            comment.save()
            return redirect('custom:custom_detail', pk=set.pk)
    else:
        form = CommentForm()

    return render(request, 'custom/custom_detail.html',{'set':set,'form':form})

def comment_remove(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('custom:custom_detail', pk=comment.custom.pk)

# 클래스형 view
class CustomDeleteView(DeleteView):
    model = Custom
    template_name = 'custom/custom_delete.html'
    success_url = reverse_lazy('board:board_set_list')

custom/templates/custom/add_comment.html
{% block content %}
    <form action="" method="POST" class="crearfix">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="save_button">저장</button>
    </form>
{% endblock %}

custom/templates/custom/custom_delete.html
{% extends 'base.html' %}

{% block content %}
<h2>정말 지우시겠습니까?</h2>
<form action=""method="post" class="register">{% csrf_token %}
    <div class="button_area">
        <button type="submit" class="button_st form_button" style="display:inline;width:48.5%">네</button> <button type="button" class="button_st form_button" style="display:inline;width:48.5%;"><a href="{% url 'custom:custom_detail' pk=object.pk %}" style="color:#fff;">아니오</a></button>
    </div>
</form>
{% endblock %}

custom/templates/custom/custom_detail.html
{% extends 'base.html' %}

{% block title %} 상세보기 {% endblock %}

{% block content %}
<div class="board_list_nav clearfix">
    <h1><a href="{% url 'board:board_home' %}">게시판</a></h1>
</div>
<!--FB SDK-->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div>
    <p>
        *NAVER 와 FaceBook 의 "API" 를 사용해서 개인의 SNS 에 컴퓨터 견적을 공유할 수 있고 "Django" 라이브러리 "imagekit" 을 이용하여
        썸네일을 제작하였습니다.<br>
        언어: Java Script 라이브러리: jQuery
    </p>
</div>
<section class="clearfix">
    <div class="set_detail_left">
        <div class="detail_set d_style">
            <h2>견적내용</h2>
            <p class="d_info">작성자: {{ set.user }} 작성일 : {{ set.create_date|date:"Y년 m월 d일 h:i" }} </p>
            <ul class="d_text">
                <span>CPU</span>
                <li onmouseout="addText('CPU')">{% if set.cpu.hard_thumbnail %}<img src="{{ set.cpu.hard_thumbnail.url }}" alt="{{ set.cpu }}">{% endif %} {% if set.cpu == None %}미선택{% else %}{{ set.cpu }}{% endif %}</li>
                <span>Board</span>
                <li onmouseover="addText('Board')">{% if set.board.hard_thumbnail %}<img src="{{ set.board.hard_thumbnail.url }}" alt="{{ set.board }}">{% endif %} {% if set.board == None %}미선택{% else %}{{ set.board }}{% endif %}</li>
                <span>RAM</span>
                <li onmouseover="addText('RAM')">{% if set.ram.hard_thumbnail %}<img src="{{ set.ram.hard_thumbnail.url }}" alt="{{ set.ram }}">{% endif %} {% if set.ram == None %}미선택{% else %}{{ set.ram }}{% endif %}</li>
                <span>VGA</span>
                <li onmouseover="addText('VGA')">{% if set.vga.hard_thumbnail %}<img src="{{ set.vga.hard_thumbnail.url }}" alt="{{ set.vga }}">{% endif %} {% if set.vga == None %}미선택{% else %}{{ set.vga }}{% endif %}</li>
                <span>Power</span>
                <li onmouseover="addText('Power')">{% if set.power.hard_thumbnail %}<img src="{{ set.power.hard_thumbnail.url }}" alt="{{ set.power }}">{% endif %} {% if set.power == None %}미선택{% else %}{{ set.power }}{% endif %}</li>
                <span>HDD</span>
                <li onmouseover="addText('HDD')">{% if set.hdd.hard_thumbnail %}<img src="{{ set.hdd.hard_thumbnail.url }}" alt="{{ set.hdd }}">{% endif %} {% if set.hdd == None %}미선택{% else %}{{ set.hdd }}{% endif %}</li>
                <span>SSD</span>
                <li onmouseover="addText('SSD')">{% if set.ssd.hard_thumbnail %}<img src="{{ set.ssd.hard_thumbnail.url }}" alt="{{ set.ssd }}">{% endif %} {% if set.ssd == None %}미선택{% else %}{{ set.ssd }}{% endif %}</li>
                <span>ODD</span>
                <li onmouseover="addText('ODD')">{% if set.odd.hard_thumbnail %}<img src="{{ set.odd.hard_thumbnail.url }}" alt="{{ set.odd }}">{% endif %} {% if set.odd == None %}미선택{% else %}{{ set.odd }}{% endif %}</li>
            </ul>
        </div>
        <div class="detail_text d_style">
            <h2>추가설명</h2>
            <p>{{ set.text }}</p>
        </div>
        <!-- SNS 공유 -->
        <div class="clearfix">
            <div class="detail_share">
                <span>
                    <script type="text/javascript" src="http://share.naver.net/js/naver_sharebutton.js"></script>
                    <script type="text/javascript">
                    new ShareNaver.makeButton({"type": "e" , "title":""});
                    </script>
                </span>
                <div class="fb-share-button" data-href="http://logia7.pythonanywhere.com/custom/{{ object.id }}" data-layout="button" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flogia7.pythonanywhere.com%2Fcustom%2F{{object.id}}&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">공유하기</a></div>
            </div>
            <div class="detail_nav">
            <a href="{% url 'board:board_set_list' %}" class="button_st">목록보기</a> {% if user == set.user %}<a href="{% url 'custom:custom_edit' pk=set.pk %}" class="button_st">수정</a> <a href="{% url 'custom:custom_delete' pk=set.pk %}" class="button_st">삭제</a>
            {% endif %}
            </div>
        </div>
    </div>
    <div class="set_detail_right">
      <h2>도움말</h2>
      <p id="guide"></p>
    </div>
</section>
<div class="comment_area clearfix">
    {% if user.is_authenticated %}
    <h3>댓글</h3>
    {% endif %}
    {% include "custom/add_comment.html" %}
</div>
{% for comment in set.custom_comments.all %}
    <div class="a_comment">
        <p class="comment_info">{{comment.author}}<span>{{comment.create_date|date:'Y년 m월 d일 h:i'}}</span></p>
        <p class="comment_text">{{comment.text}}</p>
        {% if user == set.user or user == comment.author or user.is_superuser %}
        <a href="#" class="ment_re button_st" id="{{ comment.id }}">댓글삭제</a>
        {% endif %}
    </div>
    {% empty %}
    <div class="a_comment">
        <p>등록된 댓글이 없습니다.</p>
    </div>
{% endfor %}
<script>
    $('a.ment_re').click(function() {
        ment = confirm('정말 삭제하시겠습니까?')
        pk = $('a.ment_re').attr('id')
        if (ment === true) {
            location.href="/custom/"+pk+"/comment/remove"
        } else {
            alert('취소되었습니다.')
        }
    })
    function addText(type) {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status ==200) {
        text = JSON.parse(this.responseText)
        text = text[type]
        $('p#guide').text(text)
        $('p#guide').siblings('h2').text(type+'란?');
      };
    };
    xhttp.open("GET","{% url 'get_text' %}",true)
    xhttp.send()
  };
</script>
{% endblock %}